project_name: Audimance
builds:
   - binary: audimance
     env:
        - CGO_ENABLED=0
     goos:
        - windows
        - darwin
        - linux
     goarch:
        - amd64

archives:
  - id: audimance
    format: binary
    name_template: "{{ .Binary }}.{{ .Os }}.{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
       - '^docs:'
       - '^test:'

dockers:
   - image_templates:
      - 'cycoresystems/audimance:{{ .Tag }}'
      - 'cycoresystems/audimance:{{ .Major }}'
      - 'cycoresystems/audimance:{{ .Major }}.{{ .Minor }}'
      - 'cycoresystems/audimance:latest
