language: go
env:
   - GO111MODULE=on
go:
   - "1.15"
install:
   - go get -u github.com/mjibson/esc
   - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.31.0
   - curl -sfL https://github.com/goreleaser/goreleaser/releases/download/v0.143.0/goreleaser_Linux_x86_64.tar.gz | tar xfz - -C $GOPATH/bin goreleaser
script: bash ci_check.sh
services:
   - docker
deploy:
   - provider: script
     skip_cleanup: true
     script: bash ci_release.sh
     on:
        tags: true
        condition: $TRAVIS_OS_NAME = linux

