name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - run: npm ci
    - run: npm run build

    - name: lint
      uses: golangci/golangci-lint-action@v8.0.0

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
